config/routes.rb
Rails.application.routes.draw do
  resources :agendas
  root to: 'agendas#index'
  get 'search' => 'agendas#search'
end

app/models/agenda.rb
class Agenda < ApplicationRecord
	validates :nome, presence: true
	validates :telefone, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  before_action :set_agenda, only: [:show, :edit, :update, :destroy]

  # GET /agendas
  # GET /agendas.json
  def index
    @agendas = Agenda.where(["nome LIKE ? OR contato LIKE ? OR telefone LIKE ? OR celular LIKE ?", "%#{params[:pesquisar]}%", "%#{params[:pesquisar]}%", "%#{params[:pesquisar]}%", "%#{params[:pesquisar]}%"]).order('nome ASC')
  end

  # GET /agendas/1
  # GET /agendas/1.json
  def show
  end

  # GET /agendas/new
  def new
    @agenda = Agenda.new
  end

  # GET /agendas/1/edit
  def edit
  end

  # POST /agendas
  # POST /agendas.json
  def create
    @agenda = Agenda.new(agenda_params)

    respond_to do |format|
      if @agenda.save
        format.html { redirect_to agendas_url, notice: 'Contato Criado com Sucesso.' }
        format.json { render :index, status: :created, location: @agenda }
      else
        format.html { render :index }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agendas/1
  # PATCH/PUT /agendas/1.json
  def update
    respond_to do |format|
      if @agenda.update(agenda_params)
        format.html { redirect_to agendas_url, notice: 'Contato Atualizado com Sucesso.' }
        format.json { render :index, status: :ok, location: @agenda }
      else
        format.html { render :edit }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agendas/1
  # DELETE /agendas/1.json
  def destroy
    @agenda.destroy
    respond_to do |format|
      format.html { redirect_to agendas_url, notice: 'Contato Excluído com Sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agenda
      @agenda = Agenda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agenda_params
      params.require(:agenda).permit(:nome, :contato, :telefone, :celular, :email, :endereco, :cidade, :estado, :cep)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agendas/_form.html.erb
<%= form_for(agenda) do |f| %>
  <% if agenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(agenda.errors.count, "erro") %> impediram de salvar este cadastro:</h2>

      <ul>
      <% agenda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="panel panel-default formulario">
  <div class="panel-heading">Preencha todos os campos corretamente</div>
  <div class="panel-body">

    <div class="form-group">
      <%= f.label :nome %>
      <%= f.text_field :nome, class: "form-control", required: "required" %>
    </div>
    <div class="form-group">
      <%= f.label :contato %>
      <%= f.text_field :contato, class: "form-control" %>
    </div>
    <div class="row"> 
      <div class="form-group col-xs-3">
        <%= f.label :telefone %>
        <%= f.text_field :telefone, class: "form-control", required: "required", format:"(ddd) ddd-dddd" %>
      </div>
      <div class="form-group col-xs-3">
        <%= f.label :celular %>
        <%= f.text_field :celular, class: "form-control" %>
      </div>
      <div class="form-group col-xs-3">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control", type: "email" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :endereco %>
      <%= f.text_field :endereco, class: "form-control" %>
    </div>
    <div class="row"> 
        <div class="form-group col-xs-3">
          <%= f.label :cidade %>
          <%= f.text_field :cidade, class: "form-control" %>
        </div>
        <div class="form-group col-xs-3">
          <%= f.label :estado %>
          <%= f.select :estado, ['GO', 'AC','AL','AP','AM','BA','CE','DF','ES','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'], {}, class: "form-control" %>
        </div>
        <div class="form-group col-xs-3">
          <%= f.label :cep %>
          <%= f.text_field :cep, class: "form-control" %>
        </div>
    </div>
    <div class="actions">
      <%= f.submit  "Salvar", class: "btn btn-primary"%>
    </div>
  </div>
</div>

<% end %>

app/views/agendas/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Agenda Telefônica</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-right" action="/" method="get">
        <div class="form-group">
          <input type="text" class="form-control" id="pesquisar" name="pesquisar" type="text" placeholder="Contato ou Telefone">
        </div>
        <button type="submit" class="btn btn-default">Pesquisar</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Cadastrar Contato', new_agenda_path, :class => "button", :method => :get  %> </li>
            <li><a href="#">Opção 2</a></li>
            <li><a href="#">Opção 3</a></li>
          </ul>
        </li>        
      </ul>
    </div>
  </div>
</nav>

app/views/agendas/edit.html.erb
<div class="alinhamento"><h3>Editar Contato</h3></div>

<%= render 'form', agenda: @agenda %>

app/views/agendas/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Contato</th>
      <th>Telefone</th>
      <th>Celular</th>
      <th>Email</th>
      <th>Endereco</th>
      <th>Cidade</th>
      <th>Estado</th>
      <th>Cep</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agendas.each do |agenda| %>
      <tr>
        <td><%= agenda.nome %></td>
        <td><%= agenda.contato %></td>
        <td><%= agenda.telefone %></td>
        <td><%= agenda.celular %></td>
        <td><%= agenda.email %></td>
        <td><%= agenda.endereco %></td>
        <td><%= agenda.cidade %></td>
        <td><%= agenda.estado %></td>
        <td><%= agenda.cep %></td>
        <td><%= button_to 'Editar', edit_agenda_path(agenda), :class => "btn btn-success", :method => :get  %></td>
        <td><%= button_to 'Apagar', agenda, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, :class => "btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/agendas/new.html.erb
<div class="alinhamento"><h3>Novo Contato</h3></div>

<%= render 'form', agenda: @agenda %>

app/views/agendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @agenda.nome %>
</p>

<p>
  <strong>Contato:</strong>
  <%= @agenda.contato %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @agenda.telefone %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @agenda.celular %>
</p>

<p>
  <strong>Email:</strong>
  <%= @agenda.email %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @agenda.endereco %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @agenda.cidade %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @agenda.estado %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @agenda.cep %>
</p>

<%= button_to 'Editar', edit_agenda_path(@agenda), :class => "button", :method => :get  %> |
<%= button_to 'Voltar', agendas_path, :class => "button", :method => :get  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agenda Telefônica</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  	<%= render partial: "agendas/navbar" %>
    <%= yield %>
  </body>
</html>